

CK = ['0x2A7E', '0x2A84', '0x2A7F', '0x2A80', '0x2A5A',
      '0x2A43', '0x2A42', '0x2A06', '0x2A44', '0x2A3F', '0x2AB3', '0x2A81',
      '0x2A82', '0x2A83', '0x2A58', '0x2A59', '0x2A73', '0x2A72', '0x2A01',
      '0x2AA3', '0x2A19', '0x2A1B', '0x2A1A', '0x2A49', '0x2A35', '0x2A9B',
      '0x2A9C', '0x2A38', '0x2AA4', '0x2AA5', '0x2A22', '0x2A32', '0x2A33',
      '0x2B2B', '0x2B2C', '0x2AA8', '0x2AA7', '0x2AAB', '0x2AAA', '0x2AAC',
      '0x2AA9', '0x2B29', '0x2ACE', '0x2A5C', '0x2A5B', '0x2A2B', '0x2A66',
      '0x2A65', '0x2A63', '0x2A64', '0x2A99', '0x2B2A', '0x2A85', '0x2A86',
      '0x2A08', '0x2AED', '0x2A0A', '0x2A09', '0x2A7D', '0x2A7B', '0x2A56',
      '0x2A57', '0x2A0D', '0x2A6C', '0x2A87', '0x2B2D', '0x2B2E', '0x2A0B',
      '0x2A0C', '0x2A88', '0x2A89', '0x2A26', '0x2A8A', '0x2AD9', '0x2ACC',
      '0x2ADA', '0x2A8B', '0x2AB2', '0x2AA6', '0x2A00', '0x2A04', '0x2A02',
      '0x2A03', '0x2A05', '0x2A8C', '0x2A51', '0x2A18', '0x2A34', '0x2A74',
      '0x2A27', '0x2A39', '0x2A8D', '0x2A37', '0x2A7A', '0x2A8E', '0x2A4C',
      '0x2A4A', '0x2A8F', '0x2ABA', '0x2AB9', '0x2AB7', '0x2AB8', '0x2ABB',
      '0x2A6F', '0x2B22', '0x2B25', '0x2B26', '0x2B23', '0x2B28', '0x2B27',
      '0x2B21', '0x2B20', '0x2B24', '0x2A2A', '0x2AD2', '0x2AAD', '0x2A36',
      '0x2A1E', '0x2A77', '0x2AA2', '0x2A90', '0x2AAE', '0x2A6B', '0x2A6A',
      '0x2AB1', '0x2AB', '0x2ABA0F', '0x2A67', '0x2AB5', '0x2AAF', '0x2A2C',
      '0x2AA0', '0x2AA1', '0x2A29', '0x2A91', '0x2A21', '0x2ADB', '0X2ADC',
      '0X2ADD', '0X2ADE', '0x2A24', '0x2A68', '0x2A3E', '0x2A46', '0x2AC5',
      '0x2AC', '0x2ACAC1', '0x2AC', '0x2ACAC2', '0x2AC6', '0x2AC7', '0x2ABE',
      '0x2AC4', '0x2AC0', '0x2ABF', '0x2ABD', '0x2A5F', '0x2A60', '0x2A5E',
      '0x2A50', '0x2A7', '0x2A7A2', '0x2A7A30', '0x2A69', '0x2A6D', '0x2A4E',
      '0x2A6', '0x2A2A78', '0x2B1D', '0x2B1', '0x2B1B1F', '0x2A52', '0x2A1',
      '0x2A1B3', '0x2A1A3', '0x2A2A4', '0x2A1A4B', '0x2AC9', '0x2A92',
      '0x2A40', '0x2A41', '0x2AD1', '0x2A54', '0x2A53', '0x2A55', '0x2A4F',
      '0x2A31', '0x2A3C', '0x2A10', '0x2A5D', '0x2A25', '0x2B3', '0x2B3A3B',
      '0x2A2', '0x2A2A93',
      '0x2AD0', '0x2ACF', '0x2A3D', '0x2AD7', '0x2AD', '0x2ADA47', '0x2AD8',
      '0x2AD6', '0x2AD4', '0x2A48', '0x2A23', '0x2ABC', '0x2A6E', '0x2A1F',
      '0x2A20', '0x2A1C', '0x2A1D', '0x2A94', '0x2A1', '0x2A1A15', '0x2A13',
      '0x2A16', '0x2A17', '0x2A11', '0x2A0E', '0x2AD3', '0x2ACD', '0x2A7',
      '0x2A7A70', '0x2A95', '0x2A07', '0x2AB4', '0x2A45', '0x2AB6', '0x2A9F',
      '0x2A9A', '0x2A76', '0x2A96', '0x2A97', '0x2A98', '0x2A9D', '0x2A9E',
      '0x2A79']

TK = ['Aerobic Heart Rate Lower Limit',
      'Aerobic Heart Rate Upper Limit',
      'Aerobic Threshold',
      'Age',
      'Aggregate',
      'Alert Category ID',
      'Alert Category ID Bit Mask',
      'Alert Level',
      'Alert Notification Control Point',
      'Alert Status',
      'Altitude',
      'Anaerobic Heart Rate Lower Limit',
      'Anaerobic Heart Rate Upper Limit',
      'Anaerobic Threshold',
      'Analog',
      'Analog Output',
      'Apparent Wind Direction',
      'Apparent Wind Speed',
      'Appearance',
      'Barometric Pressure Trend',
      'Battery Level',
      'Battery Level State',
      'Battery Power State',
      'Blood Pressure Feature',
      'Blood Pressure Measurement',
      'Body Composition Feature',
      'Body Composition Measurement',
      'Body Sensor Location',
      'Bond Management Control Point',
      'Bond Management Features',
      'Boot Keyboard Input Report',
      'Boot Keyboard Output Report',
      'Boot Mouse Input Report',
      'BSS Control Point',
      'BSS Response',
      'CGM Feature',
      'CGM Measurement',
      'CGM Session Run Time',
      'CGM Session Start Time',
      'CGM Specific Ops Control Point',
      'CGM Status',
      'Client Supported Features',
      'Cross Trainer Data',
      'CSC Feature',
      'CSC Measurement',
      'Current Time',
      'Cycling Power Control Point',
      'Cycling Power Feature',
      'Cycling Power Measurement',
      'Cycling Power Vector',
      'Database Change Increment',
      'Database Hash',
      'Date of Birth',
      'Date of Threshold Assessment',
      'Date Time',
      'Date UTC',
      'Day Date Time',
      'Day of Week',
      'Descriptor Value Changed',
      'Dew Point',
      'Digital',
      'Digital Output',
      'DST Offset',
      'Elevation',
      'Email Address',
      'Emergency ID',
      'Emergency Text',
      'Exact Time 100',
      'Exact Time 256',
      'Fat Burn Heart Rate Lower Limit',
      'Fat Burn Heart Rate Upper Limit',
      'Firmware Revision String',
      'First Name',
      'Fitness Machine Control Point',
      'Fitness Machine Feature',
      'Fitness Machine Status',
      'Five Zone Heart Rate Limits',
      'Floor Number',
      'Central Address Resolution',
      'Device Name',
      'Peripheral Preferred Connection Parameters',
      'Peripheral Privacy Flag',
      'Reconnection Address',
      'Service Changed',
      'Gender',
      'Glucose Feature',
      'Glucose Measurement',
      'Glucose Measurement Context',
      'Gust Factor',
      'Hardware Revision String',
      'Heart Rate Control Point',
      'Heart Rate Max',
      'Heart Rate Measurement',
      'Heat Index',
      'Height',
      'HID Control Point',
      'HID Information',
      'Hip Circumference',
      'HTTP Control Point',
      'HTTP Entity Body',
      'HTTP Headers',
      'HTTP Status Code',
      'HTTPS Security',
      'Humidity',
      'IDD Annunciation Status',
      'IDD Command Control Point',
      'IDD Command Data',
      'IDD Features',
      'IDD History Data',
      'IDD Record Access Control Point',
      'IDD Status',
      'IDD Status Changed',
      'IDD Status Reader Control Point',
      'IEEE 11073-20601 Regulatory Certification Data List',
      'Indoor Bike Data',
      'Indoor Positioning Configuration',
      'Intermediate Cuff Pressure',
      'Intermediate Temperature',
      'Irradiance',
      'Language',
      'Last Name',
      'Latitude',
      'LN Control Point',
      'LN Feature',
      'Local East Coordinate',
      'Local North Coordinate',
      'Local Time Information',
      'Location and Speed Characteristic',
      'Location Name',
      'Longitude',
      'Magnetic Declination',
      'Magnetic Flux Density – 2D',
      'Magnetic Flux Density – 3D',
      'Manufacturer Name String',
      'Maximum Recommended Heart Rate',
      'Measurement Interval',
      'Mesh Provisioning Data In',
      'Mesh Provisioning Data Out',
      'Mesh Proxy Data In',
      'Mesh Proxy Data Out',
      'Model Number String',
      'Navigation',
      'Network Availability',
      'New Alert',
      'Object Action Control Point',
      'Object Changed',
      'Object First-Created',
      'Object ID',
      'Object Last-Modified',
      'Object List Control Point',
      'Object List Filter',
      'Object Name',
      'Object Properties',
      'Object Size',
      'Object Type',
      'OTS Feature',
      'PLX Continuous Measurement Characteristic',
      'PLX Features',
      'PLX Spot-Check Measurement',
      'PnP ID',
      'Pollen Concentration',
      'Position 2D',
      'Position 3D',
      'Position Quality',
      'Pressure',
      'Protocol Mode',
      'Pulse Oximetry Control Point',
      'Rainfall',
      'RC Feature',
      'RC Settings',
      'Reconnection Configuration Control Point',
      'Record Access Control Point',
      'Reference Time Information',
      'Registered User Characteristic',
      'Removable',
      'Report',
      'Report Map',
      'Resolvable Private Address Only',
      'Resting Heart Rate',
      'Ringer Control point',
      'Ringer Setting',
      'Rower Data',
      'RSC Feature',
      'RSC Measurement',
      'SC Control Point',
      'Scan Interval Window',
      'Scan Refresh',
      'Scientific Temperature Celsius',
      'Secondary Time Zone',
      'Sensor Location',
      'Serial Number String',
      'Server Supported Features',
      'Service Required',
      'Software Revision String',
      'Sport Type for Aerobic and Anaerobic Thresholds',
      'Stair Climber Data',
      'Step Climber Data',
      'String',
      'Supported Heart Rate Range',
      'Supported Inclination Range',
      'Supported New Alert Category',
      'Supported Power Range',
      'Supported Resistance Level Range',
      'Supported Speed Range',
      'Supported Unread Alert Category',
      'System ID',
      'TDS Control Point',
      'Temperature',
      'Temperature Celsius',
      'Temperature Fahrenheit',
      'Temperature Measurement',
      'Temperature Type',
      'Three Zone Heart Rate Limits',
      'Time Accuracy',
      'Time Broadcast',
      'Time Source',
      'Time Update Control Point',
      'Time Update State',
      'Time with DST',
      'Time Zone',
      'Training Status',
      'Treadmill Data',
      'True Wind Direction',
      'True Wind Speed',
      'Two Zone Heart Rate Limit',
      'Tx Power Level',
      'Uncertainty',
      'Unread Alert Status',
      'URI',
      'User Control Point',
      'User Index',
      'UV Index',
      'VO2 Max',
      'Waist Circumference',
      'Weight',
      'Weight Measurement',
      'Weight Scale Feature',
      'Wind Chill']

CK_codes = [ck.replace('0x', '') for ck in CK]
ble_char_dict = dict(zip(CK_codes, TK))
ble_char_dict_rev = dict(zip(TK, CK_codes))
